starter:
  gateway: http://127.0.0.1:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/starter-account
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${starter.gateway}/uaa
      client:
        provider:
          uaa:
            issuer-uri: ${starter.gateway}/uaa

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8110/eureka/
