rootProject.name = "spring-cloud-starter"
include(":aggregation")
include(":frontend")
include(":infra:config")
include(":infra:gateway")
include(":infra:registry")
include(":lib:proto")
include(":lib:tests")
include(":lib:utilities")
include(":proto:api")
include(":proto:imports")
include(":proto:rpc")
include(":service:account")
include(":service:auth")
