spring:
  datasource:
    url: jdbc:mysql://localhost:3306/starter-auth
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${starter.gateway}/uaa/oauth2/jwks

starter:
  client:
    redirect-uri: http://127.0.0.1:4200/passport/callback
  gateway: http://127.0.0.1:8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8110/eureka/
