core:
  url:
    db-auth: jdbc:mysql://127.0.0.1:3306/starter_auth?allowPublicKeyRetrieval=true&useSSL=false
    endpoint: http://127.0.0.1:8080
    frontend: http://127.0.0.1:4200/passport/callback
    gateway: http://127.0.0.1:8080
    registry: http://localhost:8110/eureka
