apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-service
  name: account-service
  namespace: spring-cloud-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: starter-k8s/account-service
          imagePullPolicy: Never
          env:
            - name: JAVA_OPTS
              value: >
                -Xss512k
                -XX:MaxRAM=250m
                -Dserver.tomcat.threads.max=20
                -Dspring.profiles.active=prod
                -Dserver.port=80
          ports:
            - name: account-service
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-service
  name: account-service
  namespace: spring-cloud-starter
spec:
  type: NodePort
  ports:
    - name: "account-service"
      port: 8210
      targetPort: 80
  selector:
    app: account-service
