apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: spring-cloud-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: starter-k8s/infra-gateway
          imagePullPolicy: Never
          env:
            - name: JAVA_OPTS
              value: >
                -Xss512k
                -XX:MaxRAM=150m
                -Dserver.tomcat.threads.max=20
                -Dspring.profiles.active=prod
                -Dserver.port=80
                -Dcore.url.endpoint=http://127.0.0.1:8080
          ports:
            - name: gateway
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: spring-cloud-starter
spec:
  type: LoadBalancer
  ports:
    - name: "gateway-service"
      port: 8080
      targetPort: 80
      nodePort: 32000
  selector:
    app: gateway
