apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config
  name: config
  namespace: spring-cloud-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: starter-k8s/infra-config
          imagePullPolicy: Never
          env:
            - name: JAVA_OPTS
              value: >
                -Xss512k
                -XX:MaxRAM=150m
                -Dserver.tomcat.threads.max=20
                -Dserver.port=80
          ports:
            - name: config
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: config
  name: config
  namespace: spring-cloud-starter
spec:
  type: NodePort
  ports:
    - name: "config-service"
      port: 8100
      targetPort: 80
  selector:
    app: config
