core:
  url:
    account-service: lb://account-service
    auth-service: lb://auth-service
    db-account: jdbc:mysql://db-mysql/starter_account?useSSL=false
    db-auth: jdbc:mysql://db-mysql/starter_auth?useSSL=false
    endpoint: https://starter-api.linqu.tech
    frontend: https://starter.linqu.tech/passport/callback
    gateway: http://gateway:8080
    registry: http://registry:8110/eureka

eureka:
  client:
    serviceUrl:
      defaultZone: ${core.url.registry}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
