server:
  port: 8200
  servlet:
    context-path: /uaa

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    url: ${core.url.db-auth}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${core.url.gateway}/uaa/oauth2/jwks
